name: Testando databases

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql
        ports:
        - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: WexRobotLib
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5
      postgres:
        # Docker Hub image
        image: postgres
        ports:
        - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: WexRobotLib
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3
    - name: Checking MySQL database status
      run: |
        sudo apt-get update
        export DEBIAN_FRONTEND=noninteractive 
        wget https://dev.mysql.com/get/mysql-apt-config_0.8.26-1_all.deb
        sudo apt install ./mysql-apt-config_0.8.26-1_all.deb -y
        sudo apt update
        sudo debconf-set-selections <<< "mysql-server mysql-server/root-pass password ''"
        sudo debconf-set-selections <<< "mysql-server mysql-server/re-root-pass password ''"
        sudo apt-get update && sudo apt-get install -y mysql-server

    - name: Set up MySQL
      run: |
        sudo apt-get install -f
        sudo dpkg --configure -a
        sudo systemctl start mysql

    - name: Running Script
      run: |
        mysql -uroot -p database_name < ./MYSQL_setup.sql
